# Generated by Django 5.2.14 on 2026-06-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=50, unique=True)),
                ('relationship', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
