# Generated by Django 5.2.14 on 2026-06-03 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_referee'),
    ]

    operations = [
        migrations.AddField(
            model_name='referee',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.customer'),
        ),
    ]
