# Generated by Django 5.2.14 on 2026-05-27 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
        ('patients', '0002_product_customer_auditlog_customerkyc_creditprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employers.employer'),
        ),
    ]
