# Generated by Django 5.2.14 on 2026-06-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_referee_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referee',
            name='address',
            field=models.CharField(max_length=50),
        ),
    ]
