# Generated by Django 5.2.14 on 2026-05-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_customer_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='net_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
