# Generated by Django 5.2.14 on 2026-06-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_referee_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referee',
            name='mobile_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='referee',
            name='relationship',
            field=models.CharField(max_length=50),
        ),
    ]
