# Generated by Django 5.2.14 on 2026-05-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_customer_net_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditprofile',
            name='status',
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('LEAD', 'Lead'), ('ACTIVE', 'Active'), ('BLOCKED', 'Blocked')], default='LEAD', max_length=20),
        ),
    ]
