# Generated by Django 5.2.14 on 2026-06-10 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_referee_mobile_no_alter_referee_relationship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='net_salary',
            new_name='limit',
        ),
    ]
