# Generated by Django 5.2.14 on 2026-05-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_remove_creditprofile_status_customer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='national_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='primary_mobile',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
