# Generated by Django 5.2.14 on 2026-06-10 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_rename_net_salary_customer_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditprofile',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='patients.product'),
        ),
    ]
