# Generated by Django 5.2.14 on 2026-05-31 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_alter_customer_national_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='primary_mobile',
            field=models.CharField(max_length=20),
        ),
    ]
