# Generated by Django 5.2.14 on 2026-05-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_alter_customer_primary_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='primary_mobile',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
