# Generated by Django 5.2.14 on 2026-06-10 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_alter_creditprofile_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditprofile',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_profiles', to='patients.product'),
        ),
    ]
