# Generated by Django 5.2.14 on 2026-05-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='national_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
