# Generated by Django 5.2.14 on 2026-05-31 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repayments', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='transactions.transaction'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='repayments.paymentfor'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='repayments.paymentmethod'),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='repayments.paymentstatus'),
        ),
    ]
