# Generated by Django 5.2.14 on 2026-05-31 20:34

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('used_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('available_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.customer')),
            ],
        ),
    ]
