# Generated by Django 5.2.14 on 2026-05-27 13:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_limits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditaccount',
            name='status',
        ),
        migrations.AddField(
            model_name='creditaccount',
            name='used_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='creditaccount',
            name='available_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
