# Generated by Django 5.2.14 on 2026-06-10 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_remove_employer_total_loans_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='paybill',
        ),
    ]
