# Generated by Django 5.2.14 on 2026-06-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0003_remove_employer_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='branch',
            field=models.CharField(blank=True, default='HQ', max_length=100, null=True),
        ),
    ]
