# Generated by Django 5.2.14 on 2026-05-31 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_facility_total_loans_facility_total_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='total_loans',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='total_members',
        ),
    ]
